### ISSUE TITLE
No Toe or Camber angles?

### ISSUE THREAD

**Issue by BMarques** [AlTheSlacker/UnityCar#1]
Hello,
Have you looked into having toe and camber angles in Unity's wheel collider? I'm wondering it's possible. 

Thanks.

**Comment by AlTheSlacker** [comment]
When I wrote this, PhysX toe and camber variables were not exposed in Unity, I don't think that has changed. It's probably too much detail for this type of general utility model anyway (this is not a good starting point for a racing sim).
